# Generated by Django 4.2.6 on 2023-10-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MincePie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('cost', models.FloatField()),
                ('alcohol', models.BooleanField(default=False)),
                ('amount_in_box', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('price_per_pie', models.FloatField()),
            ],
        ),
    ]
