# Generated by Django 4.2.6 on 2023-10-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.CharField(default='bob', max_length=1000),
            preserve_default=False,
        ),
    ]
