# Generated by Django 4.2.6 on 2023-10-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_questions_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
