# Generated by Django 4.2.6 on 2023-10-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_questions_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='MincePieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField()),
                ('rated_by', models.CharField(max_length=100)),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('mince_pie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rating.mincepie')),
            ],
            options={
                'unique_together': {('mince_pie', 'rated_by')},
            },
        ),
    ]
